apiVersion: v2
dependencies:
  - name: jupyterhub
    repository: https://hub.jupyter.org/helm-chart/
    version: "*.*.*"
description: |
  This chart installs jupyterhub.
name: jupyterhub
version: "0"
